# Generated by Django 2.1.2 on 2018-10-16 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyClass',
            new_name='Youth',
        ),
    ]
