# Generated by Django 2.1.2 on 2018-10-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0002_auto_20181015_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youth',
            name='key',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
