# Generated by Django 2.1.2 on 2018-10-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0004_auto_20181016_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youth',
            name='key',
            field=models.BooleanField(),
        ),
    ]
