# Generated by Django 2.1.7 on 2019-02-27 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import key.helpers
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('is_showing', models.BooleanField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_parent', models.BooleanField(blank=True, null=True)),
                ('parent', models.CharField(blank=True, max_length=255, null=True)),
                ('ordering', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('alert', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(blank=True, null=True)),
                ('student_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alerts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttendanceItems',
            fields=[
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(default=key.helpers.getCurrentDate)),
                ('time', models.TimeField(default=key.helpers.getCurrentTime)),
                ('activity_id', models.IntegerField(blank=True, null=True)),
                ('visit_number', models.IntegerField(blank=True, null=True)),
                ('str_value', models.TextField(blank=True, null=True)),
                ('num_value', models.FloatField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'dailyattendance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalAttendanceItems',
            fields=[
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(default=key.helpers.getCurrentDate)),
                ('time', models.TimeField(default=key.helpers.getCurrentTime)),
                ('activity_id', models.IntegerField(blank=True, null=True)),
                ('visit_number', models.IntegerField(blank=True, null=True)),
                ('str_value', models.TextField(blank=True, null=True)),
                ('num_value', models.FloatField(blank=True, null=True)),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical attendance items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OldStudent',
            fields=[
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('first_attendance', models.DateField(blank=True, null=True)),
                ('number_visits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'old_students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('student_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('date', models.DateField(default=key.helpers.getCurrentDate)),
                ('time', models.TimeField(default=key.helpers.getCurrentTime)),
                ('activity_id', models.IntegerField(blank=True, null=True)),
                ('visit_number', models.IntegerField(blank=True, null=True)),
                ('daily_visits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dailyattendance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentColumn',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('is_showing', models.BooleanField(blank=True, null=True)),
                ('quick_add', models.BooleanField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('defined_options', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'studentcolumns',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('info_id', models.IntegerField(blank=True, null=True)),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('str_value', models.CharField(blank=True, max_length=20000, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('time_value', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'studentinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'students',
                'managed': True,
            },
        ),
    ]
