# Generated by Django 2.1.2 on 2019-01-17 18:38

from django.db import migrations, models
import key.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('is_showing', models.BooleanField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_parent', models.BooleanField(blank=True, null=True)),
                ('parent', models.CharField(blank=True, max_length=255, null=True)),
                ('ordering', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('alert', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(blank=True, null=True)),
                ('student_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alerts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttendanceItems',
            fields=[
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(default=key.helpers.getCurrentDate)),
                ('time', models.TimeField(default=key.helpers.getCurrentTime)),
                ('activity_id', models.IntegerField(blank=True, null=True)),
                ('visit_number', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'dailyattendance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OldStudent',
            fields=[
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('first_attendance', models.DateField(blank=True, null=True)),
                ('number_visits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'old_students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentColumn',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('is_showing', models.BooleanField(blank=True, null=True)),
                ('quick_add', models.BooleanField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('defined_options', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'studentcolumns',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('info_id', models.IntegerField(blank=True, null=True)),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('str_value', models.CharField(blank=True, max_length=500, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('time_value', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'studentinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('first_attendance', models.DateField(blank=True, null=True)),
                ('number_visits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': True,
            },
        ),
    ]
