# Generated by Django 2.1.7 on 2019-03-02 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalattendanceitems',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstudentinfo',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstudents',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalAttendanceItems',
        ),
        migrations.DeleteModel(
            name='HistoricalStudentInfo',
        ),
        migrations.DeleteModel(
            name='HistoricalStudents',
        ),
    ]
