# Generated by Django 2.1.7 on 2019-02-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='photo_value',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
