# Generated by Django 2.1.5 on 2019-01-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSuggestions',
            fields=[
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('match_name', models.TextField(blank=True, null=True)),
                ('match_key', models.TextField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'studentsuggestions',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='students',
            name='student_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
