# Generated by Django 2.1.5 on 2019-01-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='nickname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='student_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
