# Generated by Django 2.1.5 on 2019-02-06 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import key.helpers
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('key', '0002_auto_20190131_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAttendanceItems',
            fields=[
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(default=key.helpers.getCurrentDate)),
                ('time', models.TimeField(default=key.helpers.getCurrentTime)),
                ('activity_id', models.IntegerField(blank=True, null=True)),
                ('visit_number', models.IntegerField(blank=True, null=True)),
                ('str_value', models.TextField(blank=True, null=True)),
                ('num_value', models.FloatField(blank=True, null=True)),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical attendance items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
