# Generated by Django 2.1.5 on 2019-01-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0002_auto_20190125_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitySpanStudents',
            fields=[
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('student_key', models.TextField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cityspanstudents',
                'managed': True,
            },
        ),
    ]
