# Generated by Django 2.1.7 on 2019-02-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0002_auto_20190131_1916'),
        ('key', '0003_reports'),
    ]

    operations = [
    ]
