# Generated by Django 2.1.7 on 2019-02-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0003_reports'),
        ('key', '0003_historicalattendanceitems'),
    ]

    operations = [
    ]
