# Generated by Django 2.1.7 on 2019-03-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0003_historicalattendanceitems_historicalstudentinfo_historicalstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
