# Generated by Django 2.1.2 on 2018-10-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0003_auto_20181016_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youth',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
