# Generated by Django 2.1.7 on 2019-02-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0003_historicalattendanceitems'),
        ('key', '0004_merge_20190212_0211'),
    ]

    operations = [
    ]
