# Generated by Django 2.1.5 on 2019-02-13 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0004_merge_20190213_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'managed': True},
        ),
    ]
