# Generated by Django 2.1.2 on 2018-10-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0005_auto_20181016_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youth',
            name='name',
            field=models.CharField(default='chris', max_length=30),
            preserve_default=False,
        ),
    ]
