# Generated by Django 2.1.5 on 2019-02-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0005_auto_20190213_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
