# Generated by Django 2.1.7 on 2019-03-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0005_auto_20190315_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudents',
            name='id',
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
