# Generated by Django 2.1.7 on 2019-02-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0005_auto_20190221_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityspanstudents',
            name='student_key',
            field=models.TextField(),
        ),
    ]
