# Generated by Django 2.1.2 on 2018-10-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0006_auto_20181016_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youth',
            name='key',
            field=models.BooleanField(default=True),
        ),
    ]
