# Generated by Django 2.1.5 on 2019-02-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0006_auto_20190214_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
