# Generated by Django 2.1.7 on 2019-03-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0006_auto_20190315_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudentinfo',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='photo_value',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
