# Generated by Django 2.1.7 on 2019-03-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0007_auto_20190316_1928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='OldStudent',
        ),
    ]
