# Generated by Django 2.1.7 on 2019-02-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0003_historicalattendanceitems'),
        ('key', '0008_auto_20190214_1916'),
    ]

    operations = [
    ]
