# Generated by Django 2.1.7 on 2019-02-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0008_auto_20190214_1916'),
        ('key', '0005_merge_20190218_0217'),
    ]

    operations = [
    ]
