# Generated by Django 2.1.7 on 2019-02-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0009_merge_20190221_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='students',
            name='first_attendance',
        ),
        migrations.RemoveField(
            model_name='students',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='students',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='students',
            name='number_visits',
        ),
        migrations.RemoveField(
            model_name='students',
            name='student_id',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='blob_value',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='str_value',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
