# Generated by Django 2.1.7 on 2019-02-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0004_merge_20190221_1207'),
        ('key', '0010_auto_20190221_1349'),
    ]

    operations = [
    ]
