# Generated by Django 2.1.7 on 2019-02-23 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0011_merge_20190221_1514'),
        ('key', '0007_auto_20190221_1238'),
    ]

    operations = [
    ]
