# Generated by Django 2.1.7 on 2019-02-26 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0011_merge_20190221_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='blob_value',
        ),
    ]
