# Generated by Django 2.1.7 on 2019-02-24 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('key', '0012_historicalstudentcolumn_historicalstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStudentInfo',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('info_id', models.IntegerField(blank=True, null=True)),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('str_value', models.CharField(blank=True, max_length=20000, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('time_value', models.TimeField(blank=True, null=True)),
                ('blob_value', models.BinaryField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical student info',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='historicalstudentcolumn',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalStudentColumn',
        ),
    ]
