# Generated by Django 2.1.7 on 2019-02-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0013_auto_20190223_1937'),
        ('key', '0012_merge_20190222_2107'),
    ]

    operations = [
    ]
