# Generated by Django 2.1.7 on 2019-02-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0014_merge_20190226_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudents',
            name='student_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
