# Generated by Django 2.1.7 on 2019-02-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0015_historicalstudents_student_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudentinfo',
            name='blob_value',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='blob_value',
        ),
    ]
