# Generated by Django 2.1.7 on 2019-03-15 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0016_auto_20190227_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='OldStudent',
        ),
    ]
